config/routes.rb
Rails.application.routes.draw do
  resources :asset_loss_entries
  resources :asset_gain_entries
  resources :asset_gains
  resources :asset_losses
  resources :asset_countingreports
  resources :asset_countingreport_entries
  resources :asset_allocate_entries
  resources :asset_allocates
  resources :asset_disposal_entries
  resources :asset_disposals
  resources :asset_scrapping_entries
  resources :asset_pickings
  resources :asset_picking_entries
  resources :assetalters
  resources :inventory_plans
  resources :asset_turnover_detail_entries
  resources :asset_turnover_details
  resources :assetcards
  resources :assetseates
  resources :usestates
  resources :addtypes
  resources :units
  resources :assetstatuses
  resources :assettypes
 root 'sessions#new'
  resources :departments
 

  resources :users  
 
  get 'homes'  ,:to => 'homes#index'  , :as => 'homes'

  #批量删除
  post 'destroy_multiple'  ,:to => 'users#destroy_multiple'  
  post 'departments_destroy_multiple'  ,:to => 'departments#destroy_multiple'  
  post 'assettypes_destroy_multiple'  ,:to => 'assettypes#destroy_multiple'  
  post 'assetstatuses_destroy_multiple'  ,:to => 'assetstatuses#destroy_multiple'  
  post 'addtypes_destroy_multiple'  ,:to => 'addtypes#destroy_multiple'  
  post 'assetseates_destroy_multiple'  ,:to => 'assetseates#destroy_multiple'  
  post 'usestates_destroy_multiple'  ,:to => 'usestates#destroy_multiple'  
  post 'units_destroy_multiple'  ,:to => 'units#destroy_multiple'
  post 'assetcards_destroy_multiple'  ,:to => 'assetcards#destroy_multiple'
  post 'asset_recoveries_destroy_multiple'  ,:to => 'asset_recoveries#destroy_multiple'
  post 'asset_turnover_details_destroy_multiple'  ,:to => 'asset_turnover_details#destroy_multiple'
  post 'asset_allocates_destroy_multiple'  ,:to => 'asset_allocates#destroy_multiple'
  post 'asset_scrappings_destroy_multiple'  ,:to => 'asset_scrappings#destroy_multiple'
  post 'asset_pickings_destroy_multiple'  ,:to => 'asset_pickings#destroy_multiple'
  post 'assetalters_destroy_multiple'  ,:to => 'assetalters#destroy_multiple'
  post 'asset_disposals_destroy_multiple'  ,:to => 'asset_disposals#destroy_multiple'
  post 'asset_countingreports_destroy_multiple'  ,:to => 'asset_countingreports#destroy_multiple'
   
post 'asset_gains_destroy_multiple',:to => 'asset_gains#destroy_multiple'
post 'asset_losses_destroy_multiple',:to => 'asset_losses#destroy_multiple'
  #导出
  get 'users_export_all'  ,:to => 'users#export_all'
  get 'departments_export_all'  ,:to => 'departments#export_all'  
  get 'assettypes_export_all'  ,:to => 'assettypes#export_all'  
  get 'assetstatuses_export_all'  ,:to => 'assetstatuses#export_all'  
  get 'addtypes_export_all'  ,:to => 'addtypes#export_all'  
  get 'assetseates_export_all'  ,:to => 'assetseates#export_all'  
  get 'usestates_export_all'  ,:to => 'usestates#export_all'  
  get 'units_export_all'  ,:to => 'units#export_all'
  get 'assetcards_export_all'  ,:to => 'assetcards#export_all'
  get 'asset_recoveries_export_all'  ,:to => 'asset_recoveries#export_all'
  get 'asset_turnover_details_export_all'  ,:to => 'asset_turnover_details#export_all'
  get 'asset_allocates_export_all'  ,:to => 'asset_allocates#export_all'
  get 'asset_scrappings_export_all'  ,:to => 'asset_scrappings#export_all'

#导入
post 'save_multiple'  ,:to => 'users#save_multiple'  
post 'departments_save_multiple'  ,:to => 'departments#save_multiple'  
post 'assettypes_save_multiple'  ,:to => 'assettypes#save_multiple'  
post 'assetstatuses_save_multiple'  ,:to => 'assetstatuses#save_multiple'  
post 'addtypes_save_multiple'  ,:to => 'addtypes#save_multiple'  
post 'assetseates_save_multiple'  ,:to => 'assetseates#save_multiple'  
post 'usestates_save_multiple'  ,:to => 'usestates#save_multiple'  
post 'units_save_multiple'  ,:to => 'units#save_multiple'
post 'assetcards_save_multiple'  ,:to => 'assetcards#save_multiple'
post 'asset_recoveries_save_multiple'  ,:to => 'asset_recoveries#save_multiple'
post 'asset_turnover_details_save_multiple'  ,:to => 'asset_turnover_details#save_multiple'
post 'asset_allocates_save_multiple'  ,:to => 'asset_allocates#save_multiple'
post 'asset_scrappings_save_multiple'  ,:to => 'asset_scrappings#save_multiple' 
#弹窗
#选择基础资料
post 'departments_choose'  ,:to => 'departments#choose'  
post 'users_choose'  ,:to => 'users#choose'  
post 'units_choose'  ,:to => 'units#choose'  
post 'usestates_choose'  ,:to => 'usestates#choose'  
post 'assettypes_choose'  ,:to => 'assettypes#choose'   
post 'addtypes_choose'  ,:to => 'addtypes#choose'   
post 'assetseates_choose'  ,:to => 'assetseates#choose'   
post 'assetstatuses_choose'  ,:to => 'assetstatuses#choose'   
post 'assetcards_choose'  ,:to => 'assetcards#choose'  
post 'assetcards_choose_single'  ,:to => 'assetcards#choose_single'  
post 'assetseates_choose_row'  ,:to => 'assetseates#choose_row'  
post 'departments_choose_row'  ,:to => 'departments#choose_row'  
post 'users_choose_row'  ,:to => 'users#choose_row'  
  get 'login'  ,:to => 'sessions#new'  , :as => 'new_sessions'
  post 'login' ,:to   => 'sessions#create'
  delete 'logout', :to  => 'sessions#destroy' 

  get 'get_user'  ,:to => 'sessions#get_user'   
 
 

#单据头单据体一起保存
post 'asset_turnover_details_save_all',:to =>'asset_turnover_details#save_all'
post 'asset_allocates_save_all',:to =>'asset_allocates#save_all'
post 'asset_recoveries_save_all',:to =>'asset_recoveries#save_all'
post 'asset_scrappings_save_all',:to =>'asset_scrappings#save_all'
post 'asset_pickings_save_all',:to =>'asset_pickings#save_all'
post 'assetalters_save_all',:to =>'assetalters#save_all'
post 'asset_disposals_save_all',:to =>'asset_disposals#save_all'
post 'asset_countingreports_save_all',:to =>'asset_countingreports#save_all'
post 'asset_gains_save_all',:to => 'asset_gains#save_all'
post 'asset_losses_save_all',:to => 'asset_losses#save_all'
post 'assettypes_save_all',:to => 'assettypes#save_all'
#获取数据接口
get 'user_GetDataApi',:to =>'users#GetDataApi'
get 'assetalters_Get_Data',:to =>'assetalters#Get_DataApi'
get 'AssetList_Get_Data',:to =>'asset_list#Get_DataApi'
get 'asset_expiration_warning_Get_Data',:to =>'asset_expiration_warning#Get_DataApi'
get 'asset_pickings_Get_Data',:to =>'asset_pickings#Get_DataApi' 
get 'asset_disposals_Get_Data',:to =>'asset_disposals#Get_DataApi' 
get 'asset_allocates_Get_Data',:to =>'asset_allocates#Get_DataApi' 
get 'asset_countingreports_Get_Data',:to =>'asset_countingreports#Get_DataApi' 
get 'asset_gains_Get_DataApi',:to => 'asset_gains#Get_DataApi'
get 'asset_losses_Get_DataApi',:to => 'asset_losses#Get_DataApi'
get 'asset_turnover_details_Get_DataApi',:to => 'asset_turnover_details#Get_DataApi'
get 'departments_Get_DataApi',:to => 'departments#Get_DataApi'
get 'addtypes_Get_DataApi',:to => 'addtypes#Get_DataApi'
get 'assettypes_Get_DataApi',:to => 'assettypes#Get_DataApi'
get 'assetstatuses_Get_DataApi',:to => 'assetstatuses#Get_DataApi'
get 'units_Get_DataApi',:to => 'units#Get_DataApi'
get 'usestates_Get_DataApi',:to => 'usestates#Get_DataApi'
get 'assetseates_Get_DataApi',:to => 'assetseates#Get_DataApi'
#资产列表树状接口
get 'assettypes_Get_Data_Tree_Api',:to => 'assettypes#Get_Data_Tree_Api'

 

#更新状态
post 'assetcards_Update_Fbillstatus',:to => 'assetcards#Update_Fbillstatus'
post 'asset_turnover_details_Update_Fbillstatus',:to => 'asset_turnover_details#Update_Fbillstatus'
post 'assetalters_Update_Fbillstatus',:to => 'assetalters#Update_Fbillstatus'
post 'asset_pickings_Update_Fbillstatus',:to => 'asset_pickings#Update_fbillstatus'
post 'asset_disposals_Update_Fbillstatus',:to => 'asset_disposals#Update_fbillstatus'
post 'asset_allocates_Update_Fbillstatus',:to => 'asset_allocates#Update_fbillstatus'
post 'asset_countingreports_Update_Fbillstatus',:to => 'asset_countingreports#Update_fbillstatus'
post 'asset_gains_Update_Fbillstatus',:to => 'asset_gains#Update_fbillstatus'
post 'asset_losses_Update_Fbillstatus',:to => 'asset_losses#Update_fbillstatus'
post 'departments_Update_Fbillstatus',:to => 'departments#Update_fbillstatus'
post 'assetcards_Update_fbillstatus'  ,:to => 'assetcards#Update_fbillstatus'   
post 'addtypes_Update_fbillstatus'  ,:to => 'addtypes#Update_fbillstatus'   
post 'assettypes_Update_fbillstatus'  ,:to => 'assettypes#Update_fbillstatus'   
post 'assetstatuses_Update_fbillstatus'  ,:to => 'assetstatuses#Update_fbillstatus'   
post 'units_Update_fbillstatus'  ,:to => 'units#Update_fbillstatus'   
post 'usestates_Update_fbillstatus'  ,:to => 'usestates#Update_fbillstatus'   
post 'assetseates_Update_fbillstatus'  ,:to => 'assetseates#Update_fbillstatus'   


#判断是否存在未审核的资产变更单
get 'assetalters_Check_IsExist',:to => 'assetalters#Check_IsExist'

#资产实物清单
get 'AssetList_show',:to => 'asset_list#show'
#资产到期预警
get 'asset_expiration_warning_show',:to => 'asset_expiration_warning#show'

#登录界面 
post 'sessions_Login_user',:to => 'sessions#Login_user'

#检查是否允许下推
get 'asset_pickings_Check_IsPush',:to => 'asset_pickings#Check_IsPush'
get 'asset_turnover_details_Check_IsPush',:to => 'asset_turnover_details#Check_IsPush'

#检查资产卡片是否为审核、最底层
get 'assettypes_Check_Assettype',:to => 'assettypes#Check_Assettype'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 

end

app/models/asset_scrapping.rb
class AssetScrapping < ApplicationRecord
    validates :Document_number, presence: true,uniqueness: true
end

app/controllers/asset_scrappings_controller.rb
class AssetScrappingsController < ApplicationController
  before_action :set_asset_scrapping, only: [:show, :edit, :update, :destroy]

#删除
  def destroy_multiple     
    params["asset_scrappingid"].each do |i|  
      @Entry_by_Asset_Scrapping_id  = AssetScrappingEntry.where( "Asset_Scrapping_id =  ?",  "#{i}")
      @Entry_by_Asset_Scrapping_id.each do |id|  
        #删除单据体
        assetScrappingEntry_1 = AssetScrappingEntry.find_by(id: id.id)
        assetScrappingEntry_1.destroy
      end 
      #删除单据头
      AssetScrapping.destroy(i)  
  end
    respond_to do |format|
      format.html { redirect_to asset_scrappings_url notice: '删除成功！.'  }
      format.json { head :no_content }
    end
  end
  


#保存
  def  save_all 
    @id=0;
   if params["id"]==""    
    #单据新增保存 
    #创建单据头
       @assetScrapping = AssetScrapping.create!(Document_number:params["Document_number"],Date: params["Date"],Addtype: params["Addtype"],Addtype_Reason:params["Addtype_Reason"]);
       @id=@assetScrapping.id
       params["datas"].each do |i|    
        #创建单据体
       assetScrappingEntry = AssetScrappingEntry.create!(Code: i[1][0],Name: i[1][1],Unit: i[1][2],Amount: i[1][3],Scrapping_Amount: i[1][4],Asset_seat: i[1][5],Asset_Scrapping_id: @id);
       end
     else
      #单据修改保存
       @id=params["id"]; 
       @assetScrapping= AssetScrapping.find_by(id: @id) 
       #修改单据头
       @assetScrapping.update(Document_number:params["Document_number"],Date: params["Date"],Addtype: params["Addtype"],Addtype_Reason:params["Addtype_Reason"]);
       @Entry_by_Asset_Asset_Scrapping_id  = AssetScrappingEntry.where( "Asset_Scrapping_id =  ?",  "#{params[:id]}")
       @Entry_by_Asset_Asset_Scrapping_id.each do  |id| 
           if  !params[:array_id].to_a.include?(id.id.to_s)
            #相对比修改上一次的单据体记录，不存在则删除
            assetScrappingEntry_1 = AssetScrappingEntry.find_by(id: id.id)
            assetScrappingEntry_1.destroy
           end
       end 
       params[:datas].each do  |i|
         if  i[1][6].to_s == "0"
          #相对比修改时上一次的单据体记录，新增的单据体
          #创建单据体
          assetScrappingEntry_3 = AssetScrappingEntry.create!(Code: i[1][0],Name: i[1][1],Unit: i[1][2],Amount: i[1][3],Scrapping_Amount: i[1][4],Asset_seat: i[1][5],Asset_Scrapping_id: @id);
         else
          #相对比修改时上一次的单据体记录，修改的单据体
          assetScrappingEntry_2= AssetScrappingEntry.find_by(id: i[1][6])
          #更新单据体
          assetScrappingEntry_2.update(Code: i[1][0],Name: i[1][1],Unit: i[1][2],Amount: i[1][3],Scrapping_Amount: i[1][4],Asset_seat: i[1][5]);
         end 
       end       
  end    
end




  # GET /asset_scrappings
  # GET /asset_scrappings.json
  def index
    @asset_scrappings = AssetScrapping.all.page(params[:page]).per(10)
  end

  # GET /asset_scrappings/1
  # GET /asset_scrappings/1.json
  def show
  end

  # GET /asset_scrappings/new
  def new
    @asset_scrapping = AssetScrapping.new
    @entry = AssetScrappingEntry.new 
  end

  # GET /asset_scrappings/1/edit
  def edit 
    @asset_scrapping_entry  = AssetScrappingEntry.where( "Asset_Scrapping_id =  ?",  "#{params[:id]}")
  end

  # POST /asset_scrappings
  # POST /asset_scrappings.json
  def create
    @asset_scrapping = AssetScrapping.new(asset_scrapping_params) 
    respond_to do |format|
      if @asset_scrapping.save
        format.html { redirect_to @asset_scrapping, notice: 'Asset scrapping was successfully created.' }
        format.json { render :show, status: :created, location: @asset_scrapping }
      else
        format.html { render :new }
        format.json { render json: @asset_scrapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asset_scrappings/1
  # PATCH/PUT /asset_scrappings/1.json
  def update
    respond_to do |format|
      if @asset_scrapping.update(asset_scrapping_params)
        format.html { redirect_to @asset_scrapping, notice: 'Asset scrapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset_scrapping }
      else
        format.html { render :edit }
        format.json { render json: @asset_scrapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asset_scrappings/1
  # DELETE /asset_scrappings/1.json
  def destroy
    @asset_scrapping.destroy
    respond_to do |format|
      format.html { redirect_to asset_scrappings_url, notice: 'Asset scrapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset_scrapping
      @asset_scrapping = AssetScrapping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asset_scrapping_params
      params.require(:asset_scrapping).permit(:Document_number, :Date, :Addtype, :Addtype_Reason)
    end
end

app/helpers/asset_scrappings_helper.rb
module AssetScrappingsHelper
end

app/views/asset_scrappings/_form.html.erb
<%= form_with(model: asset_scrapping, local: true) do |form| %>
  <% if asset_scrapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asset_scrapping.errors.count, "error") %> prohibited this asset_scrapping from being saved:</h2>

      <ul>
        <% asset_scrapping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<p  id="id"><%= @asset_scrapping.id%></p>
     <a id="a_test"   rel="nofollow"  ><button   onclick="test1()"   type="button" class="layui-btn">保存</button></a>
    <div style="display:flex;">

     <div class="field" >
    <label class="layui-form-label"    style="  font-family: '黑体'"  for="asset_scrapping_单据编号">单据编号</label>
    <div  class="layui-input-block"> <input     class="layui-input "    placeholder="请输入单据编号"    type="text" name="asset_scrapping[Document_number]" id="asset_scrapping_Document_number"
       value=<%= @asset_scrapping.Document_number%>  ></div>
  </div> 


     <div class="field" >
    <label class="layui-form-label"    style="  font-family: '黑体'"  for="asset_scrapping_业务日期">业务日期</label>
    <div  class="layui-input-block"> <input     class="layui-input "    placeholder="请输入业务日期"    type="text" name="asset_scrapping[Date]" id="asset_scrapping_Date"
       value=<%= @asset_scrapping.Date%>  ></div>
  </div> 



     <div class="field" >
    <label class="layui-form-label"    style="  font-family: '黑体'"  for="asset_scrapping_处置方式">处置方式</label>
    <div  class="layui-input-block"> <input     class="layui-input "    placeholder="请输入处置方式"    type="text" name="asset_scrapping[Addtype]" id="asset_scrapping_Addtype"
       value=<%= @asset_scrapping.Addtype%>  ></div>
  </div> 

    </div>

   <div style="display:flex;">

     <div class="field" >
    <label class="layui-form-label"    style="  font-family: '黑体'"  for="asset_scrapping_处置原因">处置原因</label>
    <div  class="layui-input-block"> <input     class="layui-input "    placeholder="请输入处置原因"    type="text" name="asset_scrapping[Addtype_Reason]" id="asset_scrapping_Addtype_Reason"
       value=<%= @asset_scrapping.Addtype_Reason%>  ></div>
  </div> 

   </div>
 

  
<% end %>




<button onclick="addrow()">新增行</button>
<button onclick="delrow()">删除行</button>
<form id="Entry" ,action="/save_multiple">
<table    id="testid"  class="layui-table" style="text-align:center;margin:10px;0px; " >
  <colgroup>
    <col width="150"> 
    <col>
  </colgroup>
  <thead > 
    <tr >  
      <th style="text-align:center;width: 5%;"><input class='awsui-checkbox '  id='checkbox_SelectAll'  value='' type='checkbox'   onclick="selectAll(this)"></th>
      <th style="text-align:center">资产编码</th>
      <th style="text-align:center">资产名称</th> 
      <th style="text-align:center">计量单位</th>
      <th style="text-align:center">数量</th> 
      <th style="text-align:center">借用原因</th>
      <th style="text-align:center">预计归还时间</th>  
    </tr>  
  </thead>
   <tbody>
      <% if @asset_scrapping_entry.nil?%>
       <tr class="trr"  onclick =>
                <td><input class='awsui-checkbox' id='entry.ids[]' name='entry.ids[]' type='checkbox'/></td>
                <td class="tdd1" contenteditable="true"></td>
                <td class="tdd1" contenteditable="true"></td>
                <td class="tdd1" contenteditable="true"></td> 
                <td class="tdd1" contenteditable="true"></td>
                <td class="tdd1" contenteditable="true" ></td> 
                <td class="tdd1" contenteditable="true" ></td>  
              </tr>
      <%else%>
          <% @asset_scrapping_entry.each do |asset_scrapping_entry| %>
              <tr class="trr"   id=<%=asset_scrapping_entry.id%>>
                <td><input class='awsui-checkbox' id='entry.ids[]' name='entry.ids[]' type='checkbox'/></td>
                <td class="tdd1" contenteditable="true"><%= asset_scrapping_entry.Code %></td>
                <td class="tdd1" contenteditable="true"><%= asset_scrapping_entry.Name %></td>
                <td class="tdd1" contenteditable="true"><%= asset_scrapping_entry.Unit %></td>
                <td class="tdd1" contenteditable="true"><%= asset_scrapping_entry.Amount %></td>
                <td class="tdd1" contenteditable="true"><%= asset_scrapping_entry.Scrapping_Amount %></td>
                <td class="tdd1" contenteditable="true" ><%= asset_scrapping_entry.Asset_seat %></td> 
              </tr>
          <%end%>
      <%end%> 
  </tbody>
</table>  
</form> 


  <script src="https://cdn.staticfile.org/jquery/1.11.3/jquery.min.js"></script> 

<%= javascript_pack_tag 'layui'%>
<%= javascript_pack_tag 'laydate'%>
<%= stylesheet_pack_tag 'laydate'%> 

 <script>
layui.use('laydate', function(){
  var laydate = layui.laydate;
    $('.fdate').each(function(){
    laydate.render({
			elem: this     
	});
  }) 
});   
</script>
 

 <script>
//新增行
function addrow(){
   var c=document.getElementById('testid');//获得表格的信息  
   if( c.length==1)//如果是向一个空表增加一行
   {
     var x=c.insertRow(1);//向空表插入一行 
     var z=c.rows[0].cells;//如果不是空表，首先获得表格有多少列，先获取再插入新行  
     for(var i=0;i<z.length;i++)//依次向新行插入表格列数的单元格
     {
       var y=x.insertCell(i); 
     }
   }
   else
   { 
     var z=c.rows[0].cells;//如果不是空表，首先获得表格有多少列，先获取再插入新行 
     var x=c.insertRow(c.rows.length);
     x.id=0;
     for(var i=0;i<z.length;i++)//依次向新行插入表格列数的单元格
     { 
       
       var y=x.insertCell(i);  
       if(i==0)
       { 
              y.innerHTML="<input class='awsui-checkbox' id='entry.ids[]' name='entry.ids[]'  type='checkbox'/>";
       }
       else
       {
         y.setAttribute("contenteditable","true");
       }
     }
   }
}
 //删除行
function delrow(){
var x=document.getElementById("testid");
if(x.rows.length==2)
{
  alert("数据数据行至少为1行，不允许删除！");
  return false;
}
x.deleteRow(x.rows.length-1);//删除一行
}
//全选
   function selectAll(obj){ 
        //创建数组
        var arr=new Array();
        //获取所有id为“cb1”的复选框
        var items=document.getElementsByName("entry.ids[]");

        //判断复选框是否选中
        if(obj.checked)
        {
        //循环将所有name为"category"的复选框设置为选中状态
              for(var i=0;i<items.length;i++){
              //alert(items[i]);
              items[i].checked=true;
              }
        }
        else
        {
              //循环将所有name为"category"的复选框设置为非选中状态
              for(var i=0;i<items.length;i++)
              {
              //alert(items[i]);
              items[i].checked=false;
              }
        }
    }      
 </script>

<script>
function test1(){  

var  id=document.getElementById("id").innerText; 
var  Document_number=document.getElementById("asset_scrapping_Document_number").value;
var  Date=document.getElementById("asset_scrapping_Date").value;
var  Addtype=document.getElementById("asset_scrapping_Addtype").value;
var  Addtype_Reason=document.getElementById("asset_scrapping_Addtype_Reason").value; 
var array1 = new Array();
var  array_id = new Array(); 
var tb = document.getElementById('testid');    // table 的 id
var rows = tb.rows;                           // 获取表格所有行
var t=0;
for(var i = 1; i<rows.length; i++ ){
  array_id[i-1]=rows[i].id;
  var array2 = new Array();
   for(var j = 1; j<rows[i].cells.length; j++ ){    // 遍历该行的 td     
       array2[j-1]=rows[i].cells[j].innerHTML.replace('<br>', ''); 
   }
   array2[rows[i].cells.length-1]=rows[i].id;
   array1[i-1]=array2;
} 


 $.ajax({
   type:"post", 
   url:"/asset_scrappings_save_all", 
   data:{ 
     "array_id" :array_id,
      "datas": array1,
      "id":id,
      "Document_number":Document_number,
      "Date":Date,
      "Addtype":Addtype,
      "Addtype_Reason":Addtype_Reason, 
     }, 
   success: function(){
      alert("保存成功！");
     location.reload();
     },
			error :function(){
        alert("保存失败！")
        } 
 });
} 
 </script>

app/views/asset_scrappings/edit.html.erb
<h1>Editing Asset Scrapping</h1>

<%= render 'form', asset_scrapping: @asset_scrapping %>

<%= link_to 'Show', @asset_scrapping %> |
<%= link_to 'Back', asset_scrappings_path %>

app/views/asset_scrappings/new.html.erb
<h1 style="text-align:center;">资产报废单</h1>
<br>
<%= render 'form', asset_scrapping: @asset_scrapping %>

<%= link_to '返回资产报废单', asset_scrappings_path %>

app/views/asset_scrappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document number:</strong>
  <%= @asset_scrapping.Document_number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @asset_scrapping.Date %>
</p>

<p>
  <strong>Addtype:</strong>
  <%= @asset_scrapping.Addtype %>
</p>

<p>
  <strong>Addtype reason:</strong>
  <%= @asset_scrapping.Addtype_Reason %>
</p>

<%= link_to 'Edit', edit_asset_scrapping_path(@asset_scrapping) %> |
<%= link_to 'Back', asset_scrappings_path %>