config/routes.rb
Rails.application.routes.draw do
  resources :asset_loss_entries
  resources :asset_gain_entries
  resources :asset_gains
  resources :asset_losses
  resources :asset_countingreports
  resources :asset_countingreport_entries
  resources :asset_allocate_entries
  resources :asset_allocates
  resources :asset_disposal_entries
  resources :asset_disposals
  resources :asset_scrapping_entries
  resources :asset_pickings
  resources :asset_picking_entries
  resources :assetalters
  resources :inventory_plans
  resources :asset_turnover_detail_entries
  resources :asset_turnover_details
  resources :assetcards
  resources :assetseates
  resources :usestates
  resources :addtypes
  resources :units
  resources :assetstatuses
  resources :assettypes
 root 'sessions#new'
  resources :departments
 

  resources :users  
 
  get 'homes'  ,:to => 'homes#index'  , :as => 'homes'

  #批量删除
  post 'destroy_multiple'  ,:to => 'users#destroy_multiple'  
  post 'departments_destroy_multiple'  ,:to => 'departments#destroy_multiple'  
  post 'assettypes_destroy_multiple'  ,:to => 'assettypes#destroy_multiple'  
  post 'assetstatuses_destroy_multiple'  ,:to => 'assetstatuses#destroy_multiple'  
  post 'addtypes_destroy_multiple'  ,:to => 'addtypes#destroy_multiple'  
  post 'assetseates_destroy_multiple'  ,:to => 'assetseates#destroy_multiple'  
  post 'usestates_destroy_multiple'  ,:to => 'usestates#destroy_multiple'  
  post 'units_destroy_multiple'  ,:to => 'units#destroy_multiple'
  post 'assetcards_destroy_multiple'  ,:to => 'assetcards#destroy_multiple'
  post 'asset_recoveries_destroy_multiple'  ,:to => 'asset_recoveries#destroy_multiple'
  post 'asset_turnover_details_destroy_multiple'  ,:to => 'asset_turnover_details#destroy_multiple'
  post 'asset_allocates_destroy_multiple'  ,:to => 'asset_allocates#destroy_multiple'
  post 'asset_scrappings_destroy_multiple'  ,:to => 'asset_scrappings#destroy_multiple'
  post 'asset_pickings_destroy_multiple'  ,:to => 'asset_pickings#destroy_multiple'
  post 'assetalters_destroy_multiple'  ,:to => 'assetalters#destroy_multiple'
  post 'asset_disposals_destroy_multiple'  ,:to => 'asset_disposals#destroy_multiple'
  post 'asset_countingreports_destroy_multiple'  ,:to => 'asset_countingreports#destroy_multiple'
   
post 'asset_gains_destroy_multiple',:to => 'asset_gains#destroy_multiple'
post 'asset_losses_destroy_multiple',:to => 'asset_losses#destroy_multiple'
  #导出
  get 'users_export_all'  ,:to => 'users#export_all'
  get 'departments_export_all'  ,:to => 'departments#export_all'  
  get 'assettypes_export_all'  ,:to => 'assettypes#export_all'  
  get 'assetstatuses_export_all'  ,:to => 'assetstatuses#export_all'  
  get 'addtypes_export_all'  ,:to => 'addtypes#export_all'  
  get 'assetseates_export_all'  ,:to => 'assetseates#export_all'  
  get 'usestates_export_all'  ,:to => 'usestates#export_all'  
  get 'units_export_all'  ,:to => 'units#export_all'
  get 'assetcards_export_all'  ,:to => 'assetcards#export_all'
  get 'asset_recoveries_export_all'  ,:to => 'asset_recoveries#export_all'
  get 'asset_turnover_details_export_all'  ,:to => 'asset_turnover_details#export_all'
  get 'asset_allocates_export_all'  ,:to => 'asset_allocates#export_all'
  get 'asset_scrappings_export_all'  ,:to => 'asset_scrappings#export_all'

#导入
post 'save_multiple'  ,:to => 'users#save_multiple'  
post 'departments_save_multiple'  ,:to => 'departments#save_multiple'  
post 'assettypes_save_multiple'  ,:to => 'assettypes#save_multiple'  
post 'assetstatuses_save_multiple'  ,:to => 'assetstatuses#save_multiple'  
post 'addtypes_save_multiple'  ,:to => 'addtypes#save_multiple'  
post 'assetseates_save_multiple'  ,:to => 'assetseates#save_multiple'  
post 'usestates_save_multiple'  ,:to => 'usestates#save_multiple'  
post 'units_save_multiple'  ,:to => 'units#save_multiple'
post 'assetcards_save_multiple'  ,:to => 'assetcards#save_multiple'
post 'asset_recoveries_save_multiple'  ,:to => 'asset_recoveries#save_multiple'
post 'asset_turnover_details_save_multiple'  ,:to => 'asset_turnover_details#save_multiple'
post 'asset_allocates_save_multiple'  ,:to => 'asset_allocates#save_multiple'
post 'asset_scrappings_save_multiple'  ,:to => 'asset_scrappings#save_multiple' 
#弹窗
#选择基础资料
post 'departments_choose'  ,:to => 'departments#choose'  
post 'users_choose'  ,:to => 'users#choose'  
post 'units_choose'  ,:to => 'units#choose'  
post 'usestates_choose'  ,:to => 'usestates#choose'  
post 'assettypes_choose'  ,:to => 'assettypes#choose'   
post 'addtypes_choose'  ,:to => 'addtypes#choose'   
post 'assetseates_choose'  ,:to => 'assetseates#choose'   
post 'assetstatuses_choose'  ,:to => 'assetstatuses#choose'   
post 'assetcards_choose'  ,:to => 'assetcards#choose'  
post 'assetcards_choose_single'  ,:to => 'assetcards#choose_single'  
post 'assetseates_choose_row'  ,:to => 'assetseates#choose_row'  
post 'departments_choose_row'  ,:to => 'departments#choose_row'  
post 'users_choose_row'  ,:to => 'users#choose_row'  
  get 'login'  ,:to => 'sessions#new'  , :as => 'new_sessions'
  post 'login' ,:to   => 'sessions#create'
  delete 'logout', :to  => 'sessions#destroy' 

  get 'get_user'  ,:to => 'sessions#get_user'   
 
 

#单据头单据体一起保存
post 'asset_turnover_details_save_all',:to =>'asset_turnover_details#save_all'
post 'asset_allocates_save_all',:to =>'asset_allocates#save_all'
post 'asset_recoveries_save_all',:to =>'asset_recoveries#save_all'
post 'asset_scrappings_save_all',:to =>'asset_scrappings#save_all'
post 'asset_pickings_save_all',:to =>'asset_pickings#save_all'
post 'assetalters_save_all',:to =>'assetalters#save_all'
post 'asset_disposals_save_all',:to =>'asset_disposals#save_all'
post 'asset_countingreports_save_all',:to =>'asset_countingreports#save_all'
post 'asset_gains_save_all',:to => 'asset_gains#save_all'
post 'asset_losses_save_all',:to => 'asset_losses#save_all'
post 'assettypes_save_all',:to => 'assettypes#save_all'
#获取数据接口
get 'user_GetDataApi',:to =>'users#GetDataApi'
get 'assetalters_Get_Data',:to =>'assetalters#Get_DataApi'
get 'AssetList_Get_Data',:to =>'asset_list#Get_DataApi'
get 'asset_expiration_warning_Get_Data',:to =>'asset_expiration_warning#Get_DataApi'
get 'asset_pickings_Get_Data',:to =>'asset_pickings#Get_DataApi' 
get 'asset_disposals_Get_Data',:to =>'asset_disposals#Get_DataApi' 
get 'asset_allocates_Get_Data',:to =>'asset_allocates#Get_DataApi' 
get 'asset_countingreports_Get_Data',:to =>'asset_countingreports#Get_DataApi' 
get 'asset_gains_Get_DataApi',:to => 'asset_gains#Get_DataApi'
get 'asset_losses_Get_DataApi',:to => 'asset_losses#Get_DataApi'
get 'asset_turnover_details_Get_DataApi',:to => 'asset_turnover_details#Get_DataApi'
get 'departments_Get_DataApi',:to => 'departments#Get_DataApi'
get 'addtypes_Get_DataApi',:to => 'addtypes#Get_DataApi'
get 'assettypes_Get_DataApi',:to => 'assettypes#Get_DataApi'
get 'assetstatuses_Get_DataApi',:to => 'assetstatuses#Get_DataApi'
get 'units_Get_DataApi',:to => 'units#Get_DataApi'
get 'usestates_Get_DataApi',:to => 'usestates#Get_DataApi'
get 'assetseates_Get_DataApi',:to => 'assetseates#Get_DataApi'
#资产列表树状接口
get 'assettypes_Get_Data_Tree_Api',:to => 'assettypes#Get_Data_Tree_Api'

 

#更新状态
post 'assetcards_Update_Fbillstatus',:to => 'assetcards#Update_Fbillstatus'
post 'asset_turnover_details_Update_Fbillstatus',:to => 'asset_turnover_details#Update_Fbillstatus'
post 'assetalters_Update_Fbillstatus',:to => 'assetalters#Update_Fbillstatus'
post 'asset_pickings_Update_Fbillstatus',:to => 'asset_pickings#Update_fbillstatus'
post 'asset_disposals_Update_Fbillstatus',:to => 'asset_disposals#Update_fbillstatus'
post 'asset_allocates_Update_Fbillstatus',:to => 'asset_allocates#Update_fbillstatus'
post 'asset_countingreports_Update_Fbillstatus',:to => 'asset_countingreports#Update_fbillstatus'
post 'asset_gains_Update_Fbillstatus',:to => 'asset_gains#Update_fbillstatus'
post 'asset_losses_Update_Fbillstatus',:to => 'asset_losses#Update_fbillstatus'
post 'departments_Update_Fbillstatus',:to => 'departments#Update_fbillstatus'
post 'assetcards_Update_fbillstatus'  ,:to => 'assetcards#Update_fbillstatus'   
post 'addtypes_Update_fbillstatus'  ,:to => 'addtypes#Update_fbillstatus'   
post 'assettypes_Update_fbillstatus'  ,:to => 'assettypes#Update_fbillstatus'   
post 'assetstatuses_Update_fbillstatus'  ,:to => 'assetstatuses#Update_fbillstatus'   
post 'units_Update_fbillstatus'  ,:to => 'units#Update_fbillstatus'   
post 'usestates_Update_fbillstatus'  ,:to => 'usestates#Update_fbillstatus'   
post 'assetseates_Update_fbillstatus'  ,:to => 'assetseates#Update_fbillstatus'   


#判断是否存在未审核的资产变更单
get 'assetalters_Check_IsExist',:to => 'assetalters#Check_IsExist'

#资产实物清单
get 'AssetList_show',:to => 'asset_list#show'
#资产到期预警
get 'asset_expiration_warning_show',:to => 'asset_expiration_warning#show'

#登录界面 
post 'sessions_Login_user',:to => 'sessions#Login_user'

#检查是否允许下推
get 'asset_pickings_Check_IsPush',:to => 'asset_pickings#Check_IsPush'
get 'asset_turnover_details_Check_IsPush',:to => 'asset_turnover_details#Check_IsPush'

#检查资产卡片是否为审核、最底层
get 'assettypes_Check_Assettype',:to => 'assettypes#Check_Assettype'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 

end

app/models/asset_turnover_detail.rb
class AssetTurnoverDetail < ApplicationRecord
    has_many :AssetTurnoverDetailEntry
    validates :Document_number, presence: true,uniqueness: true
end

app/helpers/asset_turnover_details_helper.rb
module AssetTurnoverDetailsHelper
end

app/views/asset_turnover_details/edit.html.erb
<%= render 'form', asset_turnover_detail: @asset_turnover_detail %>
 

app/views/asset_turnover_details/index.html.erb
 <head>
   <link rel="stylesheet" type="text/css" href="https://www.layuicdn.com/layui/css/layui.css" />
     <%=stylesheet_link_tag  'totality' %>
   <style>
     .layui-table-page select {
       height: 26px;
     }
     .layui-disabled {
       background-color: #fff !important;
     }
     .layui-laypage select {
       padding: 0px;
       border-radius: 2px;
       cursor: pointer;
     }
     .layui-table-page {
       text-align: center;
     }
     .layui-laypage .layui-laypage-skip {
       color: #000;
     }
     .layui-table-box {
       position: relative;
       overflow: hidden;
       text-align: center;
     } 
   </style>
 </head>
 <h1 style="text-align:center;">资产借用/归还单</h1>
 <!--单据列表菜单-->
 <div class="layui-btn-group " style="margin:10px;0px;">
   <a data-url="/asset_turnover_details/new" data-id="asset_turnover_details" data-title="资产借用/归还单-新增"
     class="linkActive"><button type="button" class="layui-btn">新增</button></a>
   <a id="a_update" rel="nofollow" class="linkActive" data-id="edit_asset_turnover_details"
     data-title="资产借用/归还单-修改"><button type="button" class="layui-btn"
       onclick="getCheckedCheckbox_update()">修改</button></a>
   <a id="a_delete" rel="nofollow"><button onclick="model_delete('  <%=asset_turnover_details_destroy_multiple_path%>')"
       type="button" class="layui-btn">删除</button></a>
   <a rel="nofollow"><button type="button" onclick="Refresh()" class="layui-btn">刷新</button></a>
   <input type="file" id="file" style="display:none;"
     accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
   <a rel="nofollow"><button type="button" onclick="selectFile()" class="layui-btn">导入</button></a>
   <a rel="nofollow"><button type="button" onclick="exportSpecialExcel()" class="layui-btn">导出</button></a>
 </div>
 <!--单据列表-->
 <table class="layui-hide" id="asset_turnover_details" lay-filter="asset_turnover_details"></table>
 <script src="https://www.layuicdn.com/layui/layui.js"></script>
 <script src="https://cdn.staticfile.org/jquery/1.11.3/jquery.min.js"></script>
 <%=javascript_pack_tag 'tabadd' %>

 <script>
   layui.use('table', function () {
     var table = layui.table;
     table.render({
       elem: '#asset_turnover_details',
       url: '/asset_turnover_details_Get_DataApi',
       toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
         ,
       defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
         title: '刷新',
         layEvent: 'Refresh',
         icon: "layui-icon-refresh-3"
       }, { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
         title: '新增',
         layEvent: 'Add',
         icon: "layui-icon-addition"
       }],
       title: '用户数据表',
       cols: [
         [{
             type: 'checkbox'
           }, {
             field: 'Document_number',
             width: 80,
             title: '单据编号',
             sort: true
           }, {
             field: 'Type_of_business',
             width: 80,
             title: '业务类型',
             sort: true
           }, {
             field: 'Borrowing_date',
             width: 80,
             title: '借出日期',
             sort: true
           }, {
             field: 'Borrowing_Department',
             width: 80,
             title: '借出部门'
           }, {
             field: 'Loaner',
             title: '借出人',
             width: '10%',
             minWidth: 100
           } //minWidth：局部定义当前单元格的最小宽度，layui 2.2.1 新增
           , {
             field: 'fbillstatus',
             title: '单据状态',
             sort: true
           }, {
             field: 'Approver',
             title: '审核人',
             sort: true
           }, {
             field: 'Approverdate',
             title: '审核日期'
           }
         ]
       ],
       page: true,
       limits: [100, 200, 500, 1000, 2000, 10000],
       limit: 100
     });
     //监听行单击事件（双击事件为：rowDouble）
     table.on('row(test)', function (obj) {
       var data = obj.data;
       // layer.alert(JSON.stringify(data), {
       //   title: '当前行数据：'
       // }); 
       //标注选中样式
       obj.tr.addClass('layui-table-click').siblings().removeClass('layui-table-click');
     });
     //头工具栏事件
     table.on('toolbar(test)', function (obj) {
       var checkStatus = table.checkStatus(obj.config.id);
       switch (obj.event) {
         //自定义头工具栏右侧图标 - 提示
         case 'Refresh':
           Refresh();
           break;
       };
     });
   });
   $(document).on("click", ".layui-table-body table.layui-table tbody td", function () {
     if ($(this)[0].className == "") {
       var index = $(this)[0].parentElement.attributes[0].value;
       var tableBox = $(this).parents('.layui-table-box');
       //存在固定列
       tableDiv = tableBox.find(".layui-table-body.layui-table-main");
       //获取已选中列并取消选中 
       //选中单击行
       var checkCell = tableDiv.find("tr[data-index=" + index + "]").find(
         "td div.laytable-cell-checkbox div.layui-form-checkbox I");
       checkCell.click();
     }
   });
   // 将一个sheet转成最终的excel文件的blob对象，然后利用URL.createObjectURL下载
   function sheet2blob(sheet, sheetName) {
     sheetName = sheetName || 'sheet1';
     var workbook = {
       SheetNames: [sheetName],
       Sheets: {}
     };
     workbook.Sheets[sheetName] = sheet;
     // 生成excel的配置项
     var wopts = {
       bookType: 'xlsx', // 要生成的文件类型
       bookSST: false, // 是否生成Shared String Table，官方解释是，如果开启生成速度会下降，但在低版本IOS设备上有更好的兼容性
       type: 'binary'
     };
     var wbout = XLSX.write(workbook, wopts);
     var blob = new Blob([s2ab(wbout)], {
       type: "application/octet-stream"
     });
     // 字符串转ArrayBuffer
     function s2ab(s) {
       var buf = new ArrayBuffer(s.length);
       var view = new Uint8Array(buf);
       for (var i = 0; i != s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
       return buf;
     }
     return blob;
   }
   /**
    * 通用的打开下载对话框方法，没有测试过具体兼容性
    * @param url 下载地址，也可以是一个blob对象，必选
    * @param saveName 保存文件名，可选
    */
   function openDownloadDialog(url, saveName) {
     if (typeof url == 'object' && url instanceof Blob) {
       url = URL.createObjectURL(url); // 创建blob地址
     }
     var aLink = document.createElement('a');
     aLink.href = url;
     aLink.download = saveName || ''; // HTML5新增的属性，指定保存文件名，可以不要后缀，注意，file:///模式下不会生效
     var event;
     if (window.MouseEvent) event = new MouseEvent('click');
     else {
       event = document.createEvent('MouseEvents');
       event.initMouseEvent('click', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
     }
     aLink.dispatchEvent(event);
   }
   function exportSpecialExcel() {
     $.ajax({
       type: "get",
       url: "/asset_turnover_details_export_all",
       data: {},
       success: function () {
         location.reload();
       },
       error: function () {}
     });
     return;
   }
   function selectFile() {
     $("progress").show();
     document.getElementById('file').click();
   }
   $(function () {
     document.getElementById('file').addEventListener('change', function (e) {
       var files = e.target.files;
       if (files.length == 0) return;
       var f = files[0];
       if (!/\.xlsx$/g.test(f.name)) {
         alert('仅支持读取xlsx格式！');
         return;
       }
       setPercent('20');
       readWorkbookFromLocalFile(f, function (workbook) {
         readWorkbook(workbook);
       });
     });
   });
   // 读取本地excel文件
   function readWorkbookFromLocalFile(file, callback) {
     var reader = new FileReader();
     setPercent('40');
     reader.onload = function (e) {
       var data = e.target.result;
       var workbook = XLSX.read(data, {
         type: 'binary'
       });
       if (callback) callback(workbook);
     };
     reader.readAsBinaryString(file);
   }
   function readWorkbook(workbook) {
     var sheetNames = workbook.SheetNames; // 工作表名称集合
     var worksheet = workbook.Sheets[sheetNames[0]]; // 这里我们只读取第一张sheet 
     var csv = XLSX.utils.sheet_to_csv(worksheet);
     var datas = getdatas(csv);
     setPercent('80');
     SaveByAjax(datas);
     setPercent('100');
   }
   function getdatas(csv) {
     var datas = new Array();
     var rows = csv.split('\n');
     var index = 0;
     rows.pop(); // 最后一行没用的
     rows.shift(); //删掉列头
     rows.forEach(function (row, idx) {
       var columns = row.split(',');
       datas[index] = columns;
       index++;
     });
     return datas;
   }
   function SaveByAjax(datas) {
     $.ajax({
       type: "post",
       url: "/save_multiple",
       data: {
         "asset_turnover_detailsid": datas
       },
       success: function (res) {
         $("#progress").hide();
         alert('导入成功')
         location.reload();
       },
       error: function () {
         alert("导入失败")
         location.reload();
       }
     });
   }
 </script>
 <script crossorigin="anonymous"
   integrity="sha512-WNLxfP/8cVYL9sj8Jnp6et0BkubLP31jhTG9vhL/F5uEZmg5wEzKoXp1kJslzPQWwPT1eyMiSxlKCgzHLOTOTQ=="
   src="https://lib.baomitu.com/jquery/3.5.1/jquery.js"></script>
 <script type="text/javascript">
   function test1() {
     var array1 = new Array();
     var tb = document.getElementById('tab'); // table 的 id
     var rows = tb.rows; // 获取表格所有行
     var t = 0;
     for (var i = 1; i < rows.length; i++) {
       var array2 = new Array();
       for (var j = 1; j < rows[i].cells.length; j++) { // 遍历该行的 td     
         array2[j - 1] = rows[i].cells[j].innerHTML.replace('<br>', '');
       }
       array1[i - 1] = array2;
     }
     $.ajax({
       type: "post",
       url: "/save_multiple",
       data: {
         "asset_turnover_detailsid": array1
       },
       success: function (res) {
         if (res.code == 200) {
           alert("删除成功！");
           location.reload();
         }
       },
       error: function () {
         alert("删除失败！")
       }
     });
   }
   //修改单据
   function getCheckedCheckbox_update() {
     var table = layui.table;
     var checkStatus = table.checkStatus('asset_turnover_details'); //获取单据列表勾选的单据行
     if (checkStatus.data.length > 1) { //勾选的单据超过1行则提示错误信息
       alert("选择了多行数据，请选择1行！");
       document.getElementById("a_update").href = "";
       document.getElementById("a_update").dataset.url = "";
       return false;
     } else if (checkStatus.data.length == 0) { //没有勾选的单据则提示错误信息
       alert("没有选择数据，请重新选择！");
       document.getElementById("a_update").href = "";
       document.getElementById("a_update").dataset.url = "";
       return false;
     }
     //跳转到勾选的单据界面
     var asset_turnover_details_id = "/asset_turnover_details/" + checkStatus.data[0].id + "/edit";
     document.getElementById("a_update").dataset.url = asset_turnover_details_id
   }
   //删除
   function model_delete(path) {
     if (!confirm('你确定要删除吗？')) { //确认删除
       return false
     }
     var items = new Array();
     var table = layui.table;
     var checkStatus = table.checkStatus('asset_turnover_details').data; //获取单据列表勾选的单据
     for (var i = 0; i < checkStatus.length; i++) {
       items[i] = checkStatus[i].id //遍历勾选单据的集合，将单据id加入到集合中
     }
     if (items.length == 0) {
       alert("请选择单据！"); //没有勾选单据则弹出错误信息
       return;
     }
     //传递勾选单据id到后端删除接口
     var resturl = path;
     $.ajax({
       type: "post",
       url: resturl,
       data: {
         "asset_turnover_detailsid": items
       },
       success: function (res) {
         //弹出删除情况
         if (res.code == 200) {
           alert(res.message);
           location.reload();
         } else {
           alert(res.message);
         }
       }
     });
   }
   //刷新
   function Refresh() {
     location.reload([true])
   }
   $(document).ready(function () {
     $("#progress").hide();
   });
 </script>

app/views/asset_turnover_details/new.html.erb
<%= render 'form', asset_turnover_detail: @asset_turnover_detail %>
 

app/views/asset_turnover_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document number:</strong>
  <%= @asset_turnover_detail.Document_number %>
</p>

<p>
  <strong>Borrowing date:</strong>
  <%= @asset_turnover_detail.Borrowing_date %>
</p>

<p>
  <strong>Borrowing department:</strong>
  <%= @asset_turnover_detail.Borrowing_Department %>
</p>

<p>
  <strong>Borrowed to:</strong>
  <%= @asset_turnover_detail.Borrowed_To_id %>
</p>

<p>
  <strong>Loaner:</strong>
  <%= @asset_turnover_detail.Loaner %>
</p>

<%= link_to 'Edit', edit_asset_turnover_detail_path(@asset_turnover_detail) %> |
<%= link_to 'Back', asset_turnover_details_path %>