config/routes.rb
Rails.application.routes.draw do
  resources :asset_loss_entries
  resources :asset_gain_entries
  resources :asset_gains
  resources :asset_losses
  resources :asset_countingreports
  resources :asset_countingreport_entries
  resources :asset_allocate_entries
  resources :asset_allocates
  resources :asset_disposal_entries
  resources :asset_disposals
  resources :asset_scrapping_entries
  resources :asset_pickings
  resources :asset_picking_entries
  resources :assetalters
  resources :inventory_plans
  resources :asset_turnover_detail_entries
  resources :asset_turnover_details
  resources :assetcards
  resources :assetseates
  resources :usestates
  resources :addtypes
  resources :units
  resources :assetstatuses
  resources :assettypes
 root 'sessions#new'
  resources :departments
 

  resources :users  
 
  get 'homes'  ,:to => 'homes#index'  , :as => 'homes'

  #批量删除
  post 'destroy_multiple'  ,:to => 'users#destroy_multiple'  
  post 'departments_destroy_multiple'  ,:to => 'departments#destroy_multiple'  
  post 'assettypes_destroy_multiple'  ,:to => 'assettypes#destroy_multiple'  
  post 'assetstatuses_destroy_multiple'  ,:to => 'assetstatuses#destroy_multiple'  
  post 'addtypes_destroy_multiple'  ,:to => 'addtypes#destroy_multiple'  
  post 'assetseates_destroy_multiple'  ,:to => 'assetseates#destroy_multiple'  
  post 'usestates_destroy_multiple'  ,:to => 'usestates#destroy_multiple'  
  post 'units_destroy_multiple'  ,:to => 'units#destroy_multiple'
  post 'assetcards_destroy_multiple'  ,:to => 'assetcards#destroy_multiple'
  post 'asset_recoveries_destroy_multiple'  ,:to => 'asset_recoveries#destroy_multiple'
  post 'asset_turnover_details_destroy_multiple'  ,:to => 'asset_turnover_details#destroy_multiple'
  post 'asset_allocates_destroy_multiple'  ,:to => 'asset_allocates#destroy_multiple'
  post 'asset_scrappings_destroy_multiple'  ,:to => 'asset_scrappings#destroy_multiple'
  post 'asset_pickings_destroy_multiple'  ,:to => 'asset_pickings#destroy_multiple'
  post 'assetalters_destroy_multiple'  ,:to => 'assetalters#destroy_multiple'
  post 'asset_disposals_destroy_multiple'  ,:to => 'asset_disposals#destroy_multiple'
  post 'asset_countingreports_destroy_multiple'  ,:to => 'asset_countingreports#destroy_multiple'
   
post 'asset_gains_destroy_multiple',:to => 'asset_gains#destroy_multiple'
post 'asset_losses_destroy_multiple',:to => 'asset_losses#destroy_multiple'
  #导出
  get 'users_export_all'  ,:to => 'users#export_all'
  get 'departments_export_all'  ,:to => 'departments#export_all'  
  get 'assettypes_export_all'  ,:to => 'assettypes#export_all'  
  get 'assetstatuses_export_all'  ,:to => 'assetstatuses#export_all'  
  get 'addtypes_export_all'  ,:to => 'addtypes#export_all'  
  get 'assetseates_export_all'  ,:to => 'assetseates#export_all'  
  get 'usestates_export_all'  ,:to => 'usestates#export_all'  
  get 'units_export_all'  ,:to => 'units#export_all'
  get 'assetcards_export_all'  ,:to => 'assetcards#export_all'
  get 'asset_recoveries_export_all'  ,:to => 'asset_recoveries#export_all'
  get 'asset_turnover_details_export_all'  ,:to => 'asset_turnover_details#export_all'
  get 'asset_allocates_export_all'  ,:to => 'asset_allocates#export_all'
  get 'asset_scrappings_export_all'  ,:to => 'asset_scrappings#export_all'

#导入
post 'save_multiple'  ,:to => 'users#save_multiple'  
post 'departments_save_multiple'  ,:to => 'departments#save_multiple'  
post 'assettypes_save_multiple'  ,:to => 'assettypes#save_multiple'  
post 'assetstatuses_save_multiple'  ,:to => 'assetstatuses#save_multiple'  
post 'addtypes_save_multiple'  ,:to => 'addtypes#save_multiple'  
post 'assetseates_save_multiple'  ,:to => 'assetseates#save_multiple'  
post 'usestates_save_multiple'  ,:to => 'usestates#save_multiple'  
post 'units_save_multiple'  ,:to => 'units#save_multiple'
post 'assetcards_save_multiple'  ,:to => 'assetcards#save_multiple'
post 'asset_recoveries_save_multiple'  ,:to => 'asset_recoveries#save_multiple'
post 'asset_turnover_details_save_multiple'  ,:to => 'asset_turnover_details#save_multiple'
post 'asset_allocates_save_multiple'  ,:to => 'asset_allocates#save_multiple'
post 'asset_scrappings_save_multiple'  ,:to => 'asset_scrappings#save_multiple' 
#弹窗
#选择基础资料
post 'departments_choose'  ,:to => 'departments#choose'  
post 'users_choose'  ,:to => 'users#choose'  
post 'units_choose'  ,:to => 'units#choose'  
post 'usestates_choose'  ,:to => 'usestates#choose'  
post 'assettypes_choose'  ,:to => 'assettypes#choose'   
post 'addtypes_choose'  ,:to => 'addtypes#choose'   
post 'assetseates_choose'  ,:to => 'assetseates#choose'   
post 'assetstatuses_choose'  ,:to => 'assetstatuses#choose'   
post 'assetcards_choose'  ,:to => 'assetcards#choose'  
post 'assetcards_choose_single'  ,:to => 'assetcards#choose_single'  
post 'assetseates_choose_row'  ,:to => 'assetseates#choose_row'  
post 'departments_choose_row'  ,:to => 'departments#choose_row'  
post 'users_choose_row'  ,:to => 'users#choose_row'  
  get 'login'  ,:to => 'sessions#new'  , :as => 'new_sessions'
  post 'login' ,:to   => 'sessions#create'
  delete 'logout', :to  => 'sessions#destroy' 

  get 'get_user'  ,:to => 'sessions#get_user'   
 
 

#单据头单据体一起保存
post 'asset_turnover_details_save_all',:to =>'asset_turnover_details#save_all'
post 'asset_allocates_save_all',:to =>'asset_allocates#save_all'
post 'asset_recoveries_save_all',:to =>'asset_recoveries#save_all'
post 'asset_scrappings_save_all',:to =>'asset_scrappings#save_all'
post 'asset_pickings_save_all',:to =>'asset_pickings#save_all'
post 'assetalters_save_all',:to =>'assetalters#save_all'
post 'asset_disposals_save_all',:to =>'asset_disposals#save_all'
post 'asset_countingreports_save_all',:to =>'asset_countingreports#save_all'
post 'asset_gains_save_all',:to => 'asset_gains#save_all'
post 'asset_losses_save_all',:to => 'asset_losses#save_all'
post 'assettypes_save_all',:to => 'assettypes#save_all'
#获取数据接口
get 'user_GetDataApi',:to =>'users#GetDataApi'
get 'assetalters_Get_Data',:to =>'assetalters#Get_DataApi'
get 'AssetList_Get_Data',:to =>'asset_list#Get_DataApi'
get 'asset_expiration_warning_Get_Data',:to =>'asset_expiration_warning#Get_DataApi'
get 'asset_pickings_Get_Data',:to =>'asset_pickings#Get_DataApi' 
get 'asset_disposals_Get_Data',:to =>'asset_disposals#Get_DataApi' 
get 'asset_allocates_Get_Data',:to =>'asset_allocates#Get_DataApi' 
get 'asset_countingreports_Get_Data',:to =>'asset_countingreports#Get_DataApi' 
get 'asset_gains_Get_DataApi',:to => 'asset_gains#Get_DataApi'
get 'asset_losses_Get_DataApi',:to => 'asset_losses#Get_DataApi'
get 'asset_turnover_details_Get_DataApi',:to => 'asset_turnover_details#Get_DataApi'
get 'departments_Get_DataApi',:to => 'departments#Get_DataApi'
get 'addtypes_Get_DataApi',:to => 'addtypes#Get_DataApi'
get 'assettypes_Get_DataApi',:to => 'assettypes#Get_DataApi'
get 'assetstatuses_Get_DataApi',:to => 'assetstatuses#Get_DataApi'
get 'units_Get_DataApi',:to => 'units#Get_DataApi'
get 'usestates_Get_DataApi',:to => 'usestates#Get_DataApi'
get 'assetseates_Get_DataApi',:to => 'assetseates#Get_DataApi'
#资产列表树状接口
get 'assettypes_Get_Data_Tree_Api',:to => 'assettypes#Get_Data_Tree_Api'

 

#更新状态
post 'assetcards_Update_Fbillstatus',:to => 'assetcards#Update_Fbillstatus'
post 'asset_turnover_details_Update_Fbillstatus',:to => 'asset_turnover_details#Update_Fbillstatus'
post 'assetalters_Update_Fbillstatus',:to => 'assetalters#Update_Fbillstatus'
post 'asset_pickings_Update_Fbillstatus',:to => 'asset_pickings#Update_fbillstatus'
post 'asset_disposals_Update_Fbillstatus',:to => 'asset_disposals#Update_fbillstatus'
post 'asset_allocates_Update_Fbillstatus',:to => 'asset_allocates#Update_fbillstatus'
post 'asset_countingreports_Update_Fbillstatus',:to => 'asset_countingreports#Update_fbillstatus'
post 'asset_gains_Update_Fbillstatus',:to => 'asset_gains#Update_fbillstatus'
post 'asset_losses_Update_Fbillstatus',:to => 'asset_losses#Update_fbillstatus'
post 'departments_Update_Fbillstatus',:to => 'departments#Update_fbillstatus'
post 'assetcards_Update_fbillstatus'  ,:to => 'assetcards#Update_fbillstatus'   
post 'addtypes_Update_fbillstatus'  ,:to => 'addtypes#Update_fbillstatus'   
post 'assettypes_Update_fbillstatus'  ,:to => 'assettypes#Update_fbillstatus'   
post 'assetstatuses_Update_fbillstatus'  ,:to => 'assetstatuses#Update_fbillstatus'   
post 'units_Update_fbillstatus'  ,:to => 'units#Update_fbillstatus'   
post 'usestates_Update_fbillstatus'  ,:to => 'usestates#Update_fbillstatus'   
post 'assetseates_Update_fbillstatus'  ,:to => 'assetseates#Update_fbillstatus'   


#判断是否存在未审核的资产变更单
get 'assetalters_Check_IsExist',:to => 'assetalters#Check_IsExist'

#资产实物清单
get 'AssetList_show',:to => 'asset_list#show'
#资产到期预警
get 'asset_expiration_warning_show',:to => 'asset_expiration_warning#show'

#登录界面 
post 'sessions_Login_user',:to => 'sessions#Login_user'

#检查是否允许下推
get 'asset_pickings_Check_IsPush',:to => 'asset_pickings#Check_IsPush'
get 'asset_turnover_details_Check_IsPush',:to => 'asset_turnover_details#Check_IsPush'

#检查资产卡片是否为审核、最底层
get 'assettypes_Check_Assettype',:to => 'assettypes#Check_Assettype'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 

end

app/models/asset_countingreport_entry.rb
class AssetCountingreportEntry < ApplicationRecord
end

app/controllers/asset_countingreport_entries_controller.rb
class AssetCountingreportEntriesController < ApplicationController
  before_action :set_asset_countingreport_entry, only: [:show, :edit, :update, :destroy]

  # GET /asset_countingreport_entries
  # GET /asset_countingreport_entries.json
  def index
    @asset_countingreport_entries = AssetCountingreportEntry.all
  end

  # GET /asset_countingreport_entries/1
  # GET /asset_countingreport_entries/1.json
  def show
  end

  # GET /asset_countingreport_entries/new
  def new
    @asset_countingreport_entry = AssetCountingreportEntry.new
  end

  # GET /asset_countingreport_entries/1/edit
  def edit
  end

  # POST /asset_countingreport_entries
  # POST /asset_countingreport_entries.json
  def create
    @asset_countingreport_entry = AssetCountingreportEntry.new(asset_countingreport_entry_params)

    respond_to do |format|
      if @asset_countingreport_entry.save
        format.html { redirect_to @asset_countingreport_entry, notice: 'Asset countingreport entry was successfully created.' }
        format.json { render :show, status: :created, location: @asset_countingreport_entry }
      else
        format.html { render :new }
        format.json { render json: @asset_countingreport_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asset_countingreport_entries/1
  # PATCH/PUT /asset_countingreport_entries/1.json
  def update
    respond_to do |format|
      if @asset_countingreport_entry.update(asset_countingreport_entry_params)
        format.html { redirect_to @asset_countingreport_entry, notice: 'Asset countingreport entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset_countingreport_entry }
      else
        format.html { render :edit }
        format.json { render json: @asset_countingreport_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asset_countingreport_entries/1
  # DELETE /asset_countingreport_entries/1.json
  def destroy
    @asset_countingreport_entry.destroy
    respond_to do |format|
      format.html { redirect_to asset_countingreport_entries_url, notice: 'Asset countingreport entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset_countingreport_entry
      @asset_countingreport_entry = AssetCountingreportEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asset_countingreport_entry_params
      params.require(:asset_countingreport_entry).permit(:Code, :name, :Asset_type, :Unit, :Model, :Asset_status, :BookQty, :CountQty, :Variance, :Book_seat, :Book_dept, :Book_User, :Invent_seat, :Invent_dept, :InventUser, :CountDate, :Headnote, :fseq, :Asset_Countingreport_id)
    end
end

app/helpers/asset_countingreport_entries_helper.rb
module AssetCountingreportEntriesHelper
end

app/views/asset_countingreport_entries/_form.html.erb
<%= form_with(model: asset_countingreport_entry, local: true) do |form| %>
  <% if asset_countingreport_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asset_countingreport_entry.errors.count, "error") %> prohibited this asset_countingreport_entry from being saved:</h2>
      <ul>
        <% asset_countingreport_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :Code %>
    <%= form.text_field :Code %>
  </div>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :Asset_type %>
    <%= form.text_field :Asset_type %>
  </div>
  <div class="field">
    <%= form.label :Unit %>
    <%= form.text_field :Unit %>
  </div>
  <div class="field">
    <%= form.label :Model %>
    <%= form.text_field :Model %>
  </div>
  <div class="field">
    <%= form.label :Asset_status %>
    <%= form.text_field :Asset_status %>
  </div>
  <div class="field">
    <%= form.label :BookQty %>
    <%= form.text_field :BookQty %>
  </div>
  <div class="field">
    <%= form.label :CountQty %>
    <%= form.text_field :CountQty %>
  </div>
  <div class="field">
    <%= form.label :Variance %>
    <%= form.text_field :Variance %>
  </div>
  <div class="field">
    <%= form.label :Book_seat %>
    <%= form.text_field :Book_seat %>
  </div>
  <div class="field">
    <%= form.label :Book_dept %>
    <%= form.text_field :Book_dept %>
  </div>
  <div class="field">
    <%= form.label :Book_User %>
    <%= form.text_field :Book_User %>
  </div>
  <div class="field">
    <%= form.label :Invent_seat %>
    <%= form.text_field :Invent_seat %>
  </div>
  <div class="field">
    <%= form.label :Invent_dept %>
    <%= form.text_field :Invent_dept %>
  </div>
  <div class="field">
    <%= form.label :InventUser %>
    <%= form.text_field :InventUser %>
  </div>
  <div class="field">
    <%= form.label :CountDate %>
    <%= form.datetime_select :CountDate %>
  </div>
  <div class="field">
    <%= form.label :Headnote %>
    <%= form.text_field :Headnote %>
  </div>
  <div class="field">
    <%= form.label :fseq %>
    <%= form.text_field :fseq %>
  </div>
  <div class="field">
    <%= form.label :Asset_Countingreport_id %>
    <%= form.text_field :Asset_Countingreport_id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/asset_countingreport_entries/edit.html.erb
<h1>Editing Asset Countingreport Entry</h1>

<%= render 'form', asset_countingreport_entry: @asset_countingreport_entry %>

<%= link_to 'Show', @asset_countingreport_entry %> |
<%= link_to 'Back', asset_countingreport_entries_path %>

app/views/asset_countingreport_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asset Countingreport Entries</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Asset type</th>
      <th>Unit</th>
      <th>Model</th>
      <th>Asset status</th>
      <th>Bookqty</th>
      <th>Countqty</th>
      <th>Variance</th>
      <th>Book seat</th>
      <th>Book dept</th>
      <th>Book user</th>
      <th>Invent seat</th>
      <th>Invent dept</th>
      <th>Inventuser</th>
      <th>Countdate</th>
      <th>Headnote</th>
      <th>Fseq</th>
      <th>Asset countingreport</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asset_countingreport_entries.each do |asset_countingreport_entry| %>
      <tr>
        <td><%= asset_countingreport_entry.Code %></td>
        <td><%= asset_countingreport_entry.name %></td>
        <td><%= asset_countingreport_entry.Asset_type %></td>
        <td><%= asset_countingreport_entry.Unit %></td>
        <td><%= asset_countingreport_entry.Model %></td>
        <td><%= asset_countingreport_entry.Asset_status %></td>
        <td><%= asset_countingreport_entry.BookQty %></td>
        <td><%= asset_countingreport_entry.CountQty %></td>
        <td><%= asset_countingreport_entry.Variance %></td>
        <td><%= asset_countingreport_entry.Book_seat %></td>
        <td><%= asset_countingreport_entry.Book_dept %></td>
        <td><%= asset_countingreport_entry.Book_User %></td>
        <td><%= asset_countingreport_entry.Invent_seat %></td>
        <td><%= asset_countingreport_entry.Invent_dept %></td>
        <td><%= asset_countingreport_entry.InventUser %></td>
        <td><%= asset_countingreport_entry.CountDate %></td>
        <td><%= asset_countingreport_entry.Headnote %></td>
        <td><%= asset_countingreport_entry.fseq %></td>
        <td><%= asset_countingreport_entry.Asset_Countingreport_id %></td>
        <td><%= link_to 'Show', asset_countingreport_entry %></td>
        <td><%= link_to 'Edit', edit_asset_countingreport_entry_path(asset_countingreport_entry) %></td>
        <td><%= link_to 'Destroy', asset_countingreport_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset Countingreport Entry', new_asset_countingreport_entry_path %>

app/views/asset_countingreport_entries/new.html.erb
<h1>New Asset Countingreport Entry</h1>

<%= render 'form', asset_countingreport_entry: @asset_countingreport_entry %>

<%= link_to 'Back', asset_countingreport_entries_path %>

app/views/asset_countingreport_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @asset_countingreport_entry.Code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @asset_countingreport_entry.name %>
</p>

<p>
  <strong>Asset type:</strong>
  <%= @asset_countingreport_entry.Asset_type %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @asset_countingreport_entry.Unit %>
</p>

<p>
  <strong>Model:</strong>
  <%= @asset_countingreport_entry.Model %>
</p>

<p>
  <strong>Asset status:</strong>
  <%= @asset_countingreport_entry.Asset_status %>
</p>

<p>
  <strong>Bookqty:</strong>
  <%= @asset_countingreport_entry.BookQty %>
</p>

<p>
  <strong>Countqty:</strong>
  <%= @asset_countingreport_entry.CountQty %>
</p>

<p>
  <strong>Variance:</strong>
  <%= @asset_countingreport_entry.Variance %>
</p>

<p>
  <strong>Book seat:</strong>
  <%= @asset_countingreport_entry.Book_seat %>
</p>

<p>
  <strong>Book dept:</strong>
  <%= @asset_countingreport_entry.Book_dept %>
</p>

<p>
  <strong>Book user:</strong>
  <%= @asset_countingreport_entry.Book_User %>
</p>

<p>
  <strong>Invent seat:</strong>
  <%= @asset_countingreport_entry.Invent_seat %>
</p>

<p>
  <strong>Invent dept:</strong>
  <%= @asset_countingreport_entry.Invent_dept %>
</p>

<p>
  <strong>Inventuser:</strong>
  <%= @asset_countingreport_entry.InventUser %>
</p>

<p>
  <strong>Countdate:</strong>
  <%= @asset_countingreport_entry.CountDate %>
</p>

<p>
  <strong>Headnote:</strong>
  <%= @asset_countingreport_entry.Headnote %>
</p>

<p>
  <strong>Fseq:</strong>
  <%= @asset_countingreport_entry.fseq %>
</p>

<p>
  <strong>Asset countingreport:</strong>
  <%= @asset_countingreport_entry.Asset_Countingreport_id %>
</p>

<%= link_to 'Edit', edit_asset_countingreport_entry_path(@asset_countingreport_entry) %> |
<%= link_to 'Back', asset_countingreport_entries_path %>