config/routes.rb
Rails.application.routes.draw do
  resources :asset_loss_entries
  resources :asset_gain_entries
  resources :asset_gains
  resources :asset_losses
  resources :asset_countingreports
  resources :asset_countingreport_entries
  resources :asset_allocate_entries
  resources :asset_allocates
  resources :asset_disposal_entries
  resources :asset_disposals
  resources :asset_scrapping_entries
  resources :asset_pickings
  resources :asset_picking_entries
  resources :assetalters
  resources :inventory_plans
  resources :asset_turnover_detail_entries
  resources :asset_turnover_details
  resources :assetcards
  resources :assetseates
  resources :usestates
  resources :addtypes
  resources :units
  resources :assetstatuses
  resources :assettypes
 root 'sessions#new'
  resources :departments
 

  resources :users  
 
  get 'homes'  ,:to => 'homes#index'  , :as => 'homes'

  #批量删除
  post 'destroy_multiple'  ,:to => 'users#destroy_multiple'  
  post 'departments_destroy_multiple'  ,:to => 'departments#destroy_multiple'  
  post 'assettypes_destroy_multiple'  ,:to => 'assettypes#destroy_multiple'  
  post 'assetstatuses_destroy_multiple'  ,:to => 'assetstatuses#destroy_multiple'  
  post 'addtypes_destroy_multiple'  ,:to => 'addtypes#destroy_multiple'  
  post 'assetseates_destroy_multiple'  ,:to => 'assetseates#destroy_multiple'  
  post 'usestates_destroy_multiple'  ,:to => 'usestates#destroy_multiple'  
  post 'units_destroy_multiple'  ,:to => 'units#destroy_multiple'
  post 'assetcards_destroy_multiple'  ,:to => 'assetcards#destroy_multiple'
  post 'asset_recoveries_destroy_multiple'  ,:to => 'asset_recoveries#destroy_multiple'
  post 'asset_turnover_details_destroy_multiple'  ,:to => 'asset_turnover_details#destroy_multiple'
  post 'asset_allocates_destroy_multiple'  ,:to => 'asset_allocates#destroy_multiple'
  post 'asset_scrappings_destroy_multiple'  ,:to => 'asset_scrappings#destroy_multiple'
  post 'asset_pickings_destroy_multiple'  ,:to => 'asset_pickings#destroy_multiple'
  post 'assetalters_destroy_multiple'  ,:to => 'assetalters#destroy_multiple'
  post 'asset_disposals_destroy_multiple'  ,:to => 'asset_disposals#destroy_multiple'
  post 'asset_countingreports_destroy_multiple'  ,:to => 'asset_countingreports#destroy_multiple'
   
post 'asset_gains_destroy_multiple',:to => 'asset_gains#destroy_multiple'
post 'asset_losses_destroy_multiple',:to => 'asset_losses#destroy_multiple'
  #导出
  get 'users_export_all'  ,:to => 'users#export_all'
  get 'departments_export_all'  ,:to => 'departments#export_all'  
  get 'assettypes_export_all'  ,:to => 'assettypes#export_all'  
  get 'assetstatuses_export_all'  ,:to => 'assetstatuses#export_all'  
  get 'addtypes_export_all'  ,:to => 'addtypes#export_all'  
  get 'assetseates_export_all'  ,:to => 'assetseates#export_all'  
  get 'usestates_export_all'  ,:to => 'usestates#export_all'  
  get 'units_export_all'  ,:to => 'units#export_all'
  get 'assetcards_export_all'  ,:to => 'assetcards#export_all'
  get 'asset_recoveries_export_all'  ,:to => 'asset_recoveries#export_all'
  get 'asset_turnover_details_export_all'  ,:to => 'asset_turnover_details#export_all'
  get 'asset_allocates_export_all'  ,:to => 'asset_allocates#export_all'
  get 'asset_scrappings_export_all'  ,:to => 'asset_scrappings#export_all'

#导入
post 'save_multiple'  ,:to => 'users#save_multiple'  
post 'departments_save_multiple'  ,:to => 'departments#save_multiple'  
post 'assettypes_save_multiple'  ,:to => 'assettypes#save_multiple'  
post 'assetstatuses_save_multiple'  ,:to => 'assetstatuses#save_multiple'  
post 'addtypes_save_multiple'  ,:to => 'addtypes#save_multiple'  
post 'assetseates_save_multiple'  ,:to => 'assetseates#save_multiple'  
post 'usestates_save_multiple'  ,:to => 'usestates#save_multiple'  
post 'units_save_multiple'  ,:to => 'units#save_multiple'
post 'assetcards_save_multiple'  ,:to => 'assetcards#save_multiple'
post 'asset_recoveries_save_multiple'  ,:to => 'asset_recoveries#save_multiple'
post 'asset_turnover_details_save_multiple'  ,:to => 'asset_turnover_details#save_multiple'
post 'asset_allocates_save_multiple'  ,:to => 'asset_allocates#save_multiple'
post 'asset_scrappings_save_multiple'  ,:to => 'asset_scrappings#save_multiple' 
#弹窗
#选择基础资料
post 'departments_choose'  ,:to => 'departments#choose'  
post 'users_choose'  ,:to => 'users#choose'  
post 'units_choose'  ,:to => 'units#choose'  
post 'usestates_choose'  ,:to => 'usestates#choose'  
post 'assettypes_choose'  ,:to => 'assettypes#choose'   
post 'addtypes_choose'  ,:to => 'addtypes#choose'   
post 'assetseates_choose'  ,:to => 'assetseates#choose'   
post 'assetstatuses_choose'  ,:to => 'assetstatuses#choose'   
post 'assetcards_choose'  ,:to => 'assetcards#choose'  
post 'assetcards_choose_single'  ,:to => 'assetcards#choose_single'  
post 'assetseates_choose_row'  ,:to => 'assetseates#choose_row'  
post 'departments_choose_row'  ,:to => 'departments#choose_row'  
post 'users_choose_row'  ,:to => 'users#choose_row'  
  get 'login'  ,:to => 'sessions#new'  , :as => 'new_sessions'
  post 'login' ,:to   => 'sessions#create'
  delete 'logout', :to  => 'sessions#destroy' 

  get 'get_user'  ,:to => 'sessions#get_user'   
 
 

#单据头单据体一起保存
post 'asset_turnover_details_save_all',:to =>'asset_turnover_details#save_all'
post 'asset_allocates_save_all',:to =>'asset_allocates#save_all'
post 'asset_recoveries_save_all',:to =>'asset_recoveries#save_all'
post 'asset_scrappings_save_all',:to =>'asset_scrappings#save_all'
post 'asset_pickings_save_all',:to =>'asset_pickings#save_all'
post 'assetalters_save_all',:to =>'assetalters#save_all'
post 'asset_disposals_save_all',:to =>'asset_disposals#save_all'
post 'asset_countingreports_save_all',:to =>'asset_countingreports#save_all'
post 'asset_gains_save_all',:to => 'asset_gains#save_all'
post 'asset_losses_save_all',:to => 'asset_losses#save_all'
post 'assettypes_save_all',:to => 'assettypes#save_all'
#获取数据接口
get 'user_GetDataApi',:to =>'users#GetDataApi'
get 'assetalters_Get_Data',:to =>'assetalters#Get_DataApi'
get 'AssetList_Get_Data',:to =>'asset_list#Get_DataApi'
get 'asset_expiration_warning_Get_Data',:to =>'asset_expiration_warning#Get_DataApi'
get 'asset_pickings_Get_Data',:to =>'asset_pickings#Get_DataApi' 
get 'asset_disposals_Get_Data',:to =>'asset_disposals#Get_DataApi' 
get 'asset_allocates_Get_Data',:to =>'asset_allocates#Get_DataApi' 
get 'asset_countingreports_Get_Data',:to =>'asset_countingreports#Get_DataApi' 
get 'asset_gains_Get_DataApi',:to => 'asset_gains#Get_DataApi'
get 'asset_losses_Get_DataApi',:to => 'asset_losses#Get_DataApi'
get 'asset_turnover_details_Get_DataApi',:to => 'asset_turnover_details#Get_DataApi'
get 'departments_Get_DataApi',:to => 'departments#Get_DataApi'
get 'addtypes_Get_DataApi',:to => 'addtypes#Get_DataApi'
get 'assettypes_Get_DataApi',:to => 'assettypes#Get_DataApi'
get 'assetstatuses_Get_DataApi',:to => 'assetstatuses#Get_DataApi'
get 'units_Get_DataApi',:to => 'units#Get_DataApi'
get 'usestates_Get_DataApi',:to => 'usestates#Get_DataApi'
get 'assetseates_Get_DataApi',:to => 'assetseates#Get_DataApi'
#资产列表树状接口
get 'assettypes_Get_Data_Tree_Api',:to => 'assettypes#Get_Data_Tree_Api'

 

#更新状态
post 'assetcards_Update_Fbillstatus',:to => 'assetcards#Update_Fbillstatus'
post 'asset_turnover_details_Update_Fbillstatus',:to => 'asset_turnover_details#Update_Fbillstatus'
post 'assetalters_Update_Fbillstatus',:to => 'assetalters#Update_Fbillstatus'
post 'asset_pickings_Update_Fbillstatus',:to => 'asset_pickings#Update_fbillstatus'
post 'asset_disposals_Update_Fbillstatus',:to => 'asset_disposals#Update_fbillstatus'
post 'asset_allocates_Update_Fbillstatus',:to => 'asset_allocates#Update_fbillstatus'
post 'asset_countingreports_Update_Fbillstatus',:to => 'asset_countingreports#Update_fbillstatus'
post 'asset_gains_Update_Fbillstatus',:to => 'asset_gains#Update_fbillstatus'
post 'asset_losses_Update_Fbillstatus',:to => 'asset_losses#Update_fbillstatus'
post 'departments_Update_Fbillstatus',:to => 'departments#Update_fbillstatus'
post 'assetcards_Update_fbillstatus'  ,:to => 'assetcards#Update_fbillstatus'   
post 'addtypes_Update_fbillstatus'  ,:to => 'addtypes#Update_fbillstatus'   
post 'assettypes_Update_fbillstatus'  ,:to => 'assettypes#Update_fbillstatus'   
post 'assetstatuses_Update_fbillstatus'  ,:to => 'assetstatuses#Update_fbillstatus'   
post 'units_Update_fbillstatus'  ,:to => 'units#Update_fbillstatus'   
post 'usestates_Update_fbillstatus'  ,:to => 'usestates#Update_fbillstatus'   
post 'assetseates_Update_fbillstatus'  ,:to => 'assetseates#Update_fbillstatus'   


#判断是否存在未审核的资产变更单
get 'assetalters_Check_IsExist',:to => 'assetalters#Check_IsExist'

#资产实物清单
get 'AssetList_show',:to => 'asset_list#show'
#资产到期预警
get 'asset_expiration_warning_show',:to => 'asset_expiration_warning#show'

#登录界面 
post 'sessions_Login_user',:to => 'sessions#Login_user'

#检查是否允许下推
get 'asset_pickings_Check_IsPush',:to => 'asset_pickings#Check_IsPush'
get 'asset_turnover_details_Check_IsPush',:to => 'asset_turnover_details#Check_IsPush'

#检查资产卡片是否为审核、最底层
get 'assettypes_Check_Assettype',:to => 'assettypes#Check_Assettype'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 

end

app/models/assetalter.rb
class Assetalter < ApplicationRecord
end

app/helpers/assetalters_helper.rb
module AssetaltersHelper
end

app/views/assetalters/_AssetaltersModal.html.erb
 <body>
   <!-- Modal -->
   <div class="modal fade" id="assetalterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
     <div class="modal-dialog" style="width:650px;height:auto;">
       <div class="modal-content">
         <div class="modal-header">
           <!--关闭窗口按钮-->
           <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
           <h4>资产变更单记录</h4>
           <!--参数-->
           <h4 hidden="hidden" id="assetalterid" class="modal-title"></h4>
           <h4 hidden="hidden" id="assetalterModalid" class="modal-title"> <%= id%> </h4>
         </div>
         <div class="modal-body">
           <table class="layui-hide" id="assetalters" lay-filter="assetalters"></table>
         </div>
         <div class="modal-footer">
           <!--菜单列表-->
           <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
           <a id="show_assetalters" data-id="assetalters" data-title="资产变更单-查看" class="linkActive"><button type="button"
               id="showassetalters" class="layui-btn">查看</button></a>
         </div>
       </div><!-- /.modal-content -->
     </div><!-- /.modal-dialog -->
   </div><!-- /.modal -->
   <script>
     //确定按钮点击事件
     $('#showassetalters').click(function (e) {
       document.getElementById("show_assetalters").dataset.url = "/assetalters/" + $("#assetalterid").text() +
         "/edit";
     }) 
     layui.use('table', function () {
       var table = layui.table;
       table.on('tool(assetalters)', function (obj) {
         let event = obj.event;
         console.log(event);
         $("#assetalterid").text(obj.data.id);
         let tr = obj.tr;
         index = tr[0].attributes["data-index"].value;
         var tableBox = $(this).parents('.layui-table-box');
         //存在固定列
         tableDiv = tableBox.find(".layui-table-body.layui-table-main");
         //获取已选中列并取消选中 
         //选中单击行
         var checkCell = tableDiv.find("tr[data-index=" + index + "]").find(
           "td div.laytable-cell-radio div.layui-form-radio I");
         checkCell.click(); //复选框勾选 
       })
       table.on('rowDouble(assetalters)', function (obj) {
         document.getElementById("show_assetalters").dataset.url = "/assetalters/" + $("#assetalterid").text() +
           "/edit";
       })
       table.render({
         elem: '#assetalters',
         url: '/assetalters_Get_Data',
         toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
           ,
         defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
           title: '刷新',
           layEvent: 'Refresh',
           icon: "layui-icon-refresh-3"
         }, { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
           title: '新增',
           layEvent: 'Add',
           icon: "layui-icon-addition"
         }],
         title: '用户数据表',
         cols: [
           [{
               type: 'radio'
             }, {
               field: 'Fbillno',
               width: 80,
               event: "assetalter",
               title: '单据编号',
               sort: true
             } //minWidth：局部定义当前单元格的最小宽度，layui 2.2.1 新增
             , {
               field: 'fbillstatus',
               title: '单据状态',
               event: "assetalter",
               sort: true
             }, {
               field: 'assetCode',
               title: '资产编号',
               event: "assetalter",
               sort: true
             }, {
               field: 'assetname',
               event: "assetalter",
               title: '资产名称',
               sort: true
             }, {
               field: 'Approver',
               event: "assetalter",
               title: '审核人',
               sort: true
             }, {
               field: 'Approverdate',
               event: "assetalter",
               title: '审核日期'
             }
           ]
         ],
         page: true
       });
     });
   </script>
 </body>

app/views/assetalters/edit.html.erb
 

<%= render 'form', assetalter: @assetalter %>

 

app/views/assetalters/index.html.erb
 <head>
   <link rel="stylesheet" type="text/css" href="https://www.layuicdn.com/layui/css/layui.css" />
   <style>
     .layui-table-page select {
       height: 26px;
     }
     .layui-disabled {
       background-color: #fff !important;
     }
     .layui-laypage select {
       padding: 0px;
       border-radius: 2px;
       cursor: pointer;
     }
     .layui-table-page {
       text-align: center;
     }
     .layui-laypage .layui-laypage-skip {
       color: #000;
     }
     .layui-table-box {
       position: relative;
       overflow: hidden;
       text-align: center;
     }
   </style>
 </head>
 <h1 style="text-align:center;">资产变更单</h1>
 <div class="layui-btn-group " style="margin:10px;0px;">
   <a id="a_update" rel="nofollow" class="linkActive" data-id="newasset_pickings" data-title="资产领用单-修改"><button
       type="button" class="layui-btn" onclick="getCheckedCheckbox_update()">修改</button></a>
   <a id="a_delete" rel="nofollow"><button onclick="model_delete('  <%=assetalters_destroy_multiple_path%>')"
       type="button" class="layui-btn">删除</button></a>
   <a rel="nofollow"><button type="button" onclick="Refresh()" class="layui-btn">刷新</button></a>
 </div>
 <table class="layui-hide" id="assetalters" lay-filter="assetalters"></table>
 <script src="https://www.layuicdn.com/layui/layui.js"></script>
 <script src="https://cdn.staticfile.org/jquery/1.11.3/jquery.min.js"></script>
 <%=javascript_pack_tag 'tabadd' %>
 <script>
   layui.use('table', function () {
     var table = layui.table;
     table.render({
       elem: '#assetalters',
       url: '/assetalters_Get_Data',
       toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
         ,
       defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
         title: '刷新',
         layEvent: 'Refresh',
         icon: "layui-icon-refresh-3"
       }, { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
         title: '新增',
         layEvent: 'Add',
         icon: "layui-icon-addition"
       }],
       title: '用户数据表',
       cols: [
         [{
             type: 'checkbox'
           }, {
             field: 'Fbillno',
             width: 80,
             title: '单据编号',
             sort: true
           } //minWidth：局部定义当前单元格的最小宽度，layui 2.2.1 新增
           , {
             field: 'fbillstatus',
             title: '单据状态',
             sort: true
           }, {
             field: 'assetCode',
             title: '资产编号',
             sort: true
           }, {
             field: 'assetname',
             title: '资产名称',
             sort: true
           }, {
             field: 'Approver',
             title: '审核人',
             sort: true
           }, {
             field: 'Approverdate',
             title: '审核日期'
           }
         ]
       ],
       page: true
     });
     //监听行单击事件（双击事件为：rowDouble）
     table.on('row(test)', function (obj) {
       var data = obj.data;
       // layer.alert(JSON.stringify(data), {
       //   title: '当前行数据：'
       // }); 
       //标注选中样式
       obj.tr.addClass('layui-table-click').siblings().removeClass('layui-table-click');
     });
     //头工具栏事件
     table.on('toolbar(test)', function (obj) {
       var checkStatus = table.checkStatus(obj.config.id);
       switch (obj.event) {
         //自定义头工具栏右侧图标 - 提示
         case 'Refresh':
           Refresh();
           break;
       };
     });
   });
 </script>
 <script>
   $(document).on("click", ".layui-table-body table.layui-table tbody td", function () {
     if ($(this)[0].className == "") {
       var index = $(this)[0].parentElement.attributes[0].value;
       var tableBox = $(this).parents('.layui-table-box');
       //存在固定列
       tableDiv = tableBox.find(".layui-table-body.layui-table-main");
       //获取已选中列并取消选中 
       //选中单击行
       var checkCell = tableDiv.find("tr[data-index=" + index + "]").find(
         "td div.laytable-cell-checkbox div.layui-form-checkbox I");
       checkCell.click();
     }
   });
 </script>
 <script type="text/javascript">
   function test1() {
     var array1 = new Array();
     var tb = document.getElementById('tab'); // table 的 id
     var rows = tb.rows; // 获取表格所有行
     var t = 0;
     for (var i = 1; i < rows.length; i++) {
       var array2 = new Array();
       for (var j = 1; j < rows[i].cells.length; j++) { // 遍历该行的 td     
         array2[j - 1] = rows[i].cells[j].innerHTML.replace('<br>', '');
       }
       array1[i - 1] = array2;
     }
     $.ajax({
       type: "post",
       url: "/save_multiple",
       data: {
         "asset_pickingsid": array1
       },
       success: function (res) {
         if (res.code == 200) {
           alert("删除成功！");
           location.reload();
         }
       },
       error: function () {
         alert("删除失败！")
       }
     });
   }
 </script>
 <script type="text/javascript">
   function getCheckedCheckbox_update() {
     var table = layui.table;
     var checkStatus = table.checkStatus('assetalters');
     if (checkStatus.data.length > 1) {
       alert("选择了多行数据，请选择1行！");
       document.getElementById("a_update").href = "";
       return false;
     } else if (checkStatus.data.length == 0) {
       alert("没有选择数据，请重新选择！");
       document.getElementById("a_update").href = "";
       document.getElementById("a_update").dataset.url = "";
       return false;
     }
     var asset_pickings_id = "/assetalters/" + checkStatus.data[0].id + "/edit";
     document.getElementById("a_update").dataset.url = asset_pickings_id
   }
 </script>
 <script>
   function model_delete(path) {
     if (!confirm('你确定要删除吗？')) {
       return false
     }
     var items = new Array();
     var table = layui.table;
     var checkStatus = table.checkStatus('assetalters').data;
     for (var i = 0; i < checkStatus.length; i++) {
       items[i] = checkStatus[i].id
     }
     if (items.length == 0) {
       alert("请选择单据！");
       return;
     }
     var resturl = path;
     $.ajax({
       type: "post",
       url: resturl,
       data: {
         "assetaltersid": items
       },
       success: function (res) {
         if (res.code == 200) {
           alert(res.message);
           location.reload();
         } else {
           alert(res.message);
         }
       }
     });
   }
   function Refresh() {
     location.reload([true])
   }
   $(document).ready(function () {
     $("#progress").hide();
   });
 </script>

app/views/assetalters/new.html.erb
 

<%= render 'form', assetalter: @assetalter %>

 

app/views/assetalters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fbillno:</strong>
  <%= @assetalter.Fbillno %>
</p>

<p>
  <strong>Assetcode:</strong>
  <%= @assetalter.assetCode %>
</p>

<p>
  <strong>Assetname:</strong>
  <%= @assetalter.assetname %>
</p>

<p>
  <strong>Assettype:</strong>
  <%= @assetalter.Assettype_id %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @assetalter.Unit_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @assetalter.Amount %>
</p>

<p>
  <strong>Assetstatus:</strong>
  <%= @assetalter.Assetstatus_id %>
</p>

<p>
  <strong>Addtype:</strong>
  <%= @assetalter.Addtype_id %>
</p>

<p>
  <strong>Buydate:</strong>
  <%= @assetalter.BuyDate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assetalter.description %>
</p>

<p>
  <strong>Orgainize:</strong>
  <%= @assetalter.Orgainize_id %>
</p>

<p>
  <strong>Entrydate:</strong>
  <%= @assetalter.Entrydate %>
</p>

<p>
  <strong>Price:</strong>
  <%= @assetalter.Price %>
</p>

<p>
  <strong>Lastprice:</strong>
  <%= @assetalter.Lastprice %>
</p>

<p>
  <strong>Expectedperiod:</strong>
  <%= @assetalter.Expectedperiod %>
</p>

<p>
  <strong>Cnosp:</strong>
  <%= @assetalter.CNOSP %>
</p>

<p>
  <strong>Barcode:</strong>
  <%= @assetalter.barcode %>
</p>

<p>
  <strong>Mould:</strong>
  <%= @assetalter.Mould %>
</p>

<p>
  <strong>Assetseat:</strong>
  <%= @assetalter.Assetseat_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @assetalter.Client %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @assetalter.Supplier %>
</p>

<p>
  <strong>Department:</strong>
  <%= @assetalter.department_id %>
</p>

<p>
  <strong>Employeeld:</strong>
  <%= @assetalter.Employeeld %>
</p>

<p>
  <strong>Assetcode old:</strong>
  <%= @assetalter.assetCode_Old %>
</p>

<p>
  <strong>Assetname old:</strong>
  <%= @assetalter.assetname_Old %>
</p>

<p>
  <strong>Assettype id old:</strong>
  <%= @assetalter.Assettype_id_Old %>
</p>

<p>
  <strong>Unit id old:</strong>
  <%= @assetalter.Unit_id_Old %>
</p>

<p>
  <strong>Amount old:</strong>
  <%= @assetalter.Amount_Old %>
</p>

<p>
  <strong>Assetstatus id old:</strong>
  <%= @assetalter.Assetstatus_id_Old %>
</p>

<p>
  <strong>Addtype id old:</strong>
  <%= @assetalter.Addtype_id_Old %>
</p>

<p>
  <strong>Buydate old:</strong>
  <%= @assetalter.BuyDate_Old %>
</p>

<p>
  <strong>Description old:</strong>
  <%= @assetalter.description_Old %>
</p>

<p>
  <strong>Orgainize id old:</strong>
  <%= @assetalter.Orgainize_id_Old %>
</p>

<p>
  <strong>Entrydate old:</strong>
  <%= @assetalter.Entrydate_Old %>
</p>

<p>
  <strong>Price old:</strong>
  <%= @assetalter.Price_Old %>
</p>

<p>
  <strong>Lastprice old:</strong>
  <%= @assetalter.Lastprice_Old %>
</p>

<p>
  <strong>Expectedperiod old:</strong>
  <%= @assetalter.Expectedperiod_Old %>
</p>

<p>
  <strong>Cnosp old:</strong>
  <%= @assetalter.CNOSP_Old %>
</p>

<p>
  <strong>Barcode old:</strong>
  <%= @assetalter.barcode_Old %>
</p>

<p>
  <strong>Mould old:</strong>
  <%= @assetalter.Mould_Old %>
</p>

<p>
  <strong>Assetseat id old:</strong>
  <%= @assetalter.Assetseat_id_Old %>
</p>

<p>
  <strong>Client old:</strong>
  <%= @assetalter.Client_Old %>
</p>

<p>
  <strong>Supplier old:</strong>
  <%= @assetalter.Supplier_Old %>
</p>

<p>
  <strong>Department id old:</strong>
  <%= @assetalter.department_id_Old %>
</p>

<p>
  <strong>Employeeld old:</strong>
  <%= @assetalter.Employeeld_Old %>
</p>

<p>
  <strong>Fbillstatus:</strong>
  <%= @assetalter.fbillstatus %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @assetalter.Creator %>
</p>

<p>
  <strong>Createdate:</strong>
  <%= @assetalter.Createdate %>
</p>

<p>
  <strong>Approver:</strong>
  <%= @assetalter.Approver %>
</p>

<p>
  <strong>Approverdate:</strong>
  <%= @assetalter.Approverdate %>
</p>

<%= link_to 'Edit', edit_assetalter_path(@assetalter) %> |
<%= link_to 'Back', assetalters_path %>